DEBOUNCE_TYPE = custom
SRC += debounce.c

AUDIO_ENABLE = no
BACKLIGHT_ENABLE = no
BOOTMAGIC_ENABLE = yes
CAPS_WORD_ENABLE = no
CONSOLE_ENABLE = no
COMMAND_ENABLE = no
ENCODER_ENABLE = yes
EXTRAKEY_ENABLE = yes
IDLE_TIMEOUT_ENABLE = yes
LTO_ENABLE = yes
MOUSEKEY_ENABLE = no
NKRO_ENABLE = yes
RGBLIGHT_ENABLE = no
RGB_MATRIX_ENABLE = yes
TAP_DANCE_ENABLE = no